"""empty message

Revision ID: 0240bc013623
Revises: 42c06092130d
Create Date: 2021-12-07 02:52:23.040370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0240bc013623'
down_revision = '42c06092130d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('columns', sa.Column('name', sa.String(length=20), nullable=False))
    op.drop_column('columns', 'column_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('columns', sa.Column('column_name', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.drop_column('columns', 'name')
    # ### end Alembic commands ###
