"""empty message

Revision ID: 10ef6e1c630e
Revises: 437499b78c34
Create Date: 2021-12-13 06:31:31.120808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10ef6e1c630e'
down_revision = '437499b78c34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('boards', sa.Column('date', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('boards', 'date')
    # ### end Alembic commands ###
