"""empty message

Revision ID: 26f9219ef5ba
Revises: e87e972c8272
Create Date: 2022-05-19 20:10:24.043376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26f9219ef5ba'
down_revision = 'e87e972c8272'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('member_firebase_id', sa.String(), nullable=False))
    op.drop_constraint('cards_member_id_fkey', 'cards', type_='foreignkey')
    op.create_foreign_key(None, 'cards', 'members', ['member_firebase_id'], ['firebase_user_id'])
    op.drop_column('cards', 'member_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('member_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'cards', type_='foreignkey')
    op.create_foreign_key('cards_member_id_fkey', 'cards', 'members', ['member_id'], ['id'])
    op.drop_column('cards', 'member_firebase_id')
    # ### end Alembic commands ###
