"""empty message

Revision ID: 42c06092130d
Revises: 97507a25ca15
Create Date: 2021-12-05 22:49:33.603625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42c06092130d'
down_revision = '97507a25ca15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('boards', sa.Column('name', sa.String(length=15), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('boards', 'name')
    # ### end Alembic commands ###
