"""empty message

Revision ID: 437499b78c34
Revises: 7c4403cb6d80
Create Date: 2021-12-10 22:50:18.384618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '437499b78c34'
down_revision = '7c4403cb6d80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('boards', 'team_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('boards', 'team_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
