"""empty message

Revision ID: 49f16db5b91e
Revises: 10ef6e1c630e
Create Date: 2022-05-13 15:43:54.427497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49f16db5b91e'
down_revision = '10ef6e1c630e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('teams_board_id_fkey', 'teams', type_='foreignkey')
    op.drop_column('teams', 'board_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('board_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('teams_board_id_fkey', 'teams', 'boards', ['board_id'], ['id'])
    # ### end Alembic commands ###
