"""empty message

Revision ID: 7c4403cb6d80
Revises: 948c556726fd
Create Date: 2021-12-10 22:45:09.646453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c4403cb6d80'
down_revision = '948c556726fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('board_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('teams_board_id_fkey', 'teams', 'boards', ['board_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint('teams_board_id_fkey', 'teams', type_='foreignkey')
    # op.drop_column('teams', 'board_id')
    # ### end Alembic commands ###
    pass
