"""empty message

Revision ID: 948c556726fd
Revises: 0b4e0ac4d9a3
Create Date: 2021-12-10 22:41:44.833951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '948c556726fd'
down_revision = '0b4e0ac4d9a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('boards', sa.Column('team_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'boards', 'teams', ['team_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'boards', type_='foreignkey')
    op.drop_column('boards', 'team_id')
    # ### end Alembic commands ###
