"""empty message

Revision ID: a19694fa748e
Revises: c00e9bcb5727
Create Date: 2022-05-27 02:48:05.210786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a19694fa748e'
down_revision = 'c00e9bcb5727'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'teams_members', 'teams', ['team_id'], ['id'])
    op.create_foreign_key(None, 'teams_members', 'members', ['member_id'], ['firebase_user_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teams_members', type_='foreignkey')
    op.drop_constraint(None, 'teams_members', type_='foreignkey')
    # ### end Alembic commands ###
