"""empty message

Revision ID: c00e9bcb5727
Revises: 26f9219ef5ba
Create Date: 2022-05-20 17:12:05.628025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c00e9bcb5727'
down_revision = '26f9219ef5ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('role', sa.Enum('Member', 'TeamMember', 'TeamManager', name='Role'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('members', 'role')
    # ### end Alembic commands ###
