"""empty message

Revision ID: e1102e6ecd80
Revises: 
Create Date: 2021-12-03 17:49:03.500029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1102e6ecd80'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('boards', sa.Column('member_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'boards', 'members', ['member_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'boards', type_='foreignkey')
    op.drop_column('boards', 'member_id')
    # ### end Alembic commands ###
