"""empty message

Revision ID: e87e972c8272
Revises: 681fe94a376e
Create Date: 2022-05-14 14:36:46.036925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e87e972c8272'
down_revision = '681fe94a376e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('boards', sa.Column('member_firebase_id', sa.String(), nullable=False))
    op.create_foreign_key(None, 'boards', 'members', ['member_firebase_id'], ['firebase_user_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'boards', type_='foreignkey')
    op.drop_column('boards', 'member_firebase_id')
    # ### end Alembic commands ###
